title: 'Aprendizaje y Enseñanza de la Tecnología'
subtitle: 'Itinerario de Computación. Grado en Ingeniería Informática. ULL. Curso 2018/2019'
theme: jekyll-theme-midnight
description: '3º. 2º cuatrimestre. Itinerario de Computación. Grado en Ingeniería Informática. ULL'
acronym: AET
exclude: [ 'Arona-winter-course', 'dsi1819', 'dsi1819-introduccion', 'tema0-introduccion-a-pl/practicas/code']
baseurl: '/introduccion'
url: https://ULL-ESIT-PL-1819.github.io/introduccion
show_downloads: false
calendario_academico: https://www.ull.es/estudios-docencia/calendario-academico/
horarios_examenes: https://www.ull.es/grados/ingenieria-informatica/informacion-academica/horarios-y-calendario-examenes/
calendario_examenes: https://docs.google.com/document/d/1j5rJyULD1c42UV4o-g85puuPlbO-DNFmaobn_vnKgKw/edit#
horarios_tutorias: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
google_plus: https://plus.google.com/u/1/communities/101901734024125937720
organization: 
  url: https://github.com/ULL-ESIT-PL-1920
  name: ULL-ESIT-PL-1920
  master: https://github.com/ULL-ESIT-PL-1819/introduccion/tree/master/
apuntes_repo: https://github.com/ULL-ESIT-PL-1819/introduccion/
campus_virtual: https://campusvirtual.ull.es/ingenieriaytecnologia/course/view.php?id=201911070
calificador: https://campusvirtual.ull.es/ingenieriaytecnologia/1920/grade/report/grader/index.php?id=201911070
tareas: https://campusvirtual.ull.es/ingenieriaytecnologia/1920/mod/assign/index.php?id=201911070
profesor: https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/
profesor_github: crguezl
chat: https://chat.google.com/u/1/room/AAAANx1edCg
bull_permanente: https://puntoq.ull.es/permalink/f
covid_ull: https://campusvirtual.ull.es/doctoradoyposgrado/course/view.php?id=201913946
dsi:
  apuntes: https://ull-esit-dsi-1819.github.io/dsi-1819/
sytws:
  url: https://ull-mii-sytws-1920.github.io/
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: https://classroom.github.com/classrooms/53047670-ull-esit-pl-1920
  name: ULL-ESIT-PL-1920
temas:
  - title: 'Tema 0: Introducción a la Asignatura'
    url: /tema0-introduccion-a-pl/
    hover: 'Introduccion-al-Procesamiento-de-Lenguajes' 
practicas:
  - title: 00cuestionarioghalu
    myurl: https://campusvirtual.ull.es/ingenieriaytecnologia/1920/mod/assign/view.php?id=14658
    name: Tarea Formulario Usuario de Github
  - title: 01comunidadgpluspl
    myurl: https://campusvirtual.ull.es/ingenieriaytecnologia/1920/mod/assign/view.php?id=14657
    name: Tarea Comunidad G+ de PL


