title: 'Procesadores de Lenguajes'
subtitle: 'Itinerario de Computación. Grado en Ingeniería Informática. ULL. Curso 2018/2019'
theme: jekyll-theme-midnight
description: '3º. 2º cuatrimestre. Itinerario de Computación. Grado en Ingeniería Informática. ULL'
acronym: PL
exclude: [ 'Arona-winter-course', 'dsi1819', 'dsi1819-introduccion', 'tema0-introduccion-a-pl/practicas/code']
baseurl: '/introduccion'
url: https://ULL-ESIT-PL-1819.github.io/introduccion
show_downloads: false
calendario_academico: https://www.ull.es/estudios-docencia/calendario-academico/
horarios_examenes: https://www.ull.es/grados/ingenieria-informatica/informacion-academica/horarios-y-calendario-examenes/
calendario_examenes: https://docs.google.com/document/d/1j5rJyULD1c42UV4o-g85puuPlbO-DNFmaobn_vnKgKw/edit#
horarios_tutorias: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
organization: 
  url: https://github.com/ULL-ESIT-PL-1920/introduccion
  name: ULL-ESIT-PL-1920
  master: https://github.com/ULL-ESIT-PL-1819/introduccion/tree/master/
apuntes_repo: https://github.com/ULL-ESIT-PL-1819/introduccion/
campus_virtual: https://campusvirtual.ull.es/1920/course/view.php?id=201911070
calificador: https://campusvirtual.ull.es/1920/grade/report/grader/index.php?id=201911070
tareas: https://campusvirtual.ull.es/1920/mod/assign/index.php?id=201911070
profesor: https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/
profesor_github: crguezl
bull_permanente: https://puntoq.ull.es/permalink/f
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: https://classroom.github.com/classrooms/53047670-ull-esit-pl-1920
  name: ULL-ESIT-PL-1920
temas:
  - title: 'Tema 0: Introducción a la Asignatura'
    url: /tema0-introduccion-a-pl/guia-docente.html
    hover: 'Presentación'
  - title: 'Tema 1: Introducción a JavaScript'
    url: /tema1-introduccion-a-javascript/
    hover: 'Intro-a-js'
practicas:
  - title: 00cuestionarioghalu
    myurl: https://campusvirtual.ull.es/1920/mod/assign/view.php?id=14658
    name: Tarea Formulario Usuario de Github
  - title: 01comunidadgpluspl
    myurl: https://campusvirtual.ull.es/1920/mod/assign/view.php?id=14657
    name: Tarea Comunidad G+ de PL
  - title: 02pb-gh-campus-expert
    myurl: /tema0-introduccion-a-pl/practicas/pb-gh-campus-expert/
    name: Práctica pb-gh-campus-expert
  - title: 03p0-t0-esprima-logging
    myurl: /tema0-introduccion-a-pl/practicas/p0-t0-esprima-logging
    name: Práctica p0-t0-esprima-logging
  - title: 04p1-t1-iaas
    myurl: /tema1-introduccion-a-javascript/practicas/p1-t1-iaas/
    name: Práctica p1-t1-iaas
  - title: 05p2-t1-vscode
    myurl: /tema1-introduccion-a-javascript/practicas/p2-t1-vscode/
    name: Práctica p2-t1-vscode
